In this step of lab 1 you will code and understand basic steps of image classification, including cross-validation, using a KNN classifier.

Answers to the questions embedded in this code should be added to the file "exampleSubmission.py".


In [12]:
#First, let's load in the data we created in the previous step.
import pickle

with open("testTrainLab1.pickle", "rb") as f:
    labData = pickle.load(f)

print("Confirm we have the expected 50,000 training Images:")
print(len(labData["X_train"]))
print(len(labData["y_train"]))

print("\nConfirm we have the expected 10,000 test Images:")
print(len(labData["X_test"]))
print(len(labData["y_test"]))

print("\nConfirm the first image in our training set is a 32x32x3 matrix of values, representing a 32x32 image with 3 bands of color:")
print(labData["X_train"][0].shape)

print("\nConfirm our y observations make sense - i.e., an integer between 0 and 9 representing one of the 10 classes in CIFAR")
print(labData["y_train"][0])
print(max(labData["y_train"]))
print(min(labData["y_train"]))

Confirm we have the expected 50,000 training Images:
50000
50000

Confirm we have the expected 10,000 test Images:
10000
10000

Confirm the first image in our training set is a 32x32x3 matrix of values, representing a 32x32 image with 3 bands of color:
(32, 32, 3)

Confirm our first y observation makes sense - i.e., an integer between 0 and 9 representing one of the 10 classes in CIFAR
6
9
0


In [19]:
import numpy as np
#Here, we're going to reshape our image data
#Right now, it's in matrices - i.e., the below will print out a matrix, 
#where each line of the matrix is a list:
print(labData["X_train"][0])

#While we could use that data, it's less effecient than doing array
#manipulations, where every value is in a single list.  Using array manipulations
#Greatly speeds up our code - while that isn't terribly important for this lab,
#it will be critical in the future, so let's get used to it now.
#This will reshape into rows - we'll also go ahead and unpack from our dict.
X_train = np.reshape(labData["X_train"], (labData["X_train"].shape[0], -1))
X_test = np.reshape(labData["X_test"], (labData["X_test"].shape[0], -1))
print("\nReshaped Matrix - note the first value is still '59', then '62', just like in the matrix form - it's just a long list now:")
print(X_train[0])

[[[ 59.  62.  63.]
  [ 43.  46.  45.]
  [ 50.  48.  43.]
  ...
  [158. 132. 108.]
  [152. 125. 102.]
  [148. 124. 103.]]

 [[ 16.  20.  20.]
  [  0.   0.   0.]
  [ 18.   8.   0.]
  ...
  [123.  88.  55.]
  [119.  83.  50.]
  [122.  87.  57.]]

 [[ 25.  24.  21.]
  [ 16.   7.   0.]
  [ 49.  27.   8.]
  ...
  [118.  84.  50.]
  [120.  84.  50.]
  [109.  73.  42.]]

 ...

 [[208. 170.  96.]
  [201. 153.  34.]
  [198. 161.  26.]
  ...
  [160. 133.  70.]
  [ 56.  31.   7.]
  [ 53.  34.  20.]]

 [[180. 139.  96.]
  [173. 123.  42.]
  [186. 144.  30.]
  ...
  [184. 148.  94.]
  [ 97.  62.  34.]
  [ 83.  53.  34.]]

 [[177. 144. 116.]
  [168. 129.  94.]
  [179. 142.  87.]
  ...
  [216. 184. 140.]
  [151. 118.  84.]
  [123.  92.  72.]]]

Reshaped Matrix - note the first value is still '59', then '62', just like in the matrix form - it's just a long list now:
[ 59.  62.  63. ... 123.  92.  72.]
